### ISSUE TITLE
Footer Section: If you forgot to remove the default hoverstate behaviour color in the footer links and will still implement it please style it according to the design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Corp-City-Real-Estate#18]
![image](https://cloud.githubusercontent.com/assets/13363508/13344366/4b6508de-dc90-11e5-82b1-70a18ad92bc4.png)

**Comment by Santosh-titan** [comment]
Reference to this issue no #19 , I have implemented footer links hover style like text links.

**Comment by maehtitan** [comment]
it doesn't styled according to the design layout, currently it is gray which I believe the default color
