### ISSUE TITLE
Is it an indicator that "-Post Title" means the heading of the item listed below? coz no titles were displaying currently, they are all addresses with status and amount and the downside of it is you will have a hard time figuring out at the admin which specific custom post you will be editing 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Corp-City-Real-Estate#2]
Why not make the address as the post title and not implementing it as ACF since no google maps needed for this section?

![image](https://cloud.githubusercontent.com/assets/13363508/13311996/e583052e-dbcd-11e5-9b91-308244b6f777.png)
![image](https://cloud.githubusercontent.com/assets/13363508/13312441/847b0c14-dbd1-11e5-8cad-9e8d5b48e020.png)

**Comment by Santosh-titan** [comment]
I think we should use ACF field because there is a filter for "Suburb".
