### ISSUE TITLE
Is the Services page included in the implementation including the Gallery page?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Corp-City-Real-Estate#34]
![image](https://cloud.githubusercontent.com/assets/13363508/13387773/0f47e1a2-def5-11e5-9f28-2322b8b9a837.png)
![image](https://cloud.githubusercontent.com/assets/13363508/13387787/269f27ca-def5-11e5-98ab-3ef1de97cb2b.png)

**Comment by Santosh-titan** [comment]
We don't have design for "Gallery and Services" pages, So we can remove this pages.
