### ISSUE TITLE
For Sale and Rent Single pages: No pop-up form found when clicking the Email a Friend button

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Corp-City-Real-Estate#6]
![image](https://cloud.githubusercontent.com/assets/13363508/13315272/b56b6a5e-dbe4-11e5-819c-33c1c49f72e7.png)

**Comment by Santosh-titan** [comment]
In scope Captcha field was mentioned, But we should not use it for popup form because Ajax validation won't work by using Captcha field instead of that we are using "Honyspot".

**Comment by maehtitan** [comment]
As per Bernard, you can totally removed the Anti-Spam Honeypot  code when implementing the Captcha

**Comment by Santosh-titan** [comment]
As your request I have implemented captacha field, But because of it form Ajax validations won't work same mentioned in my previous comment

**Comment by maehtitan** [comment]
Hi @Santosh-titan, Sorry I will prefer your first comment to not implement the captcha coz it's really hard to test the validation when it is existing it will closed the form when validating it
